---
# Usuario de la VM (por defecto de Azure -> azureuser)
vm_user: "{{ tf_vm_admin_username }}"

# Nginx secure en Podman
nginx_secure_repo: "podman/nginx-secure"
nginx_secure_image: "{{ acr_login_server }}/{{ nginx_secure_repo }}:{{ cp2_tag }}"
nginx_secure_name: "nginx-secure"

# Puerto HTTPS público (host) donde se expone el contenedor (contenedor siempre 443)
nginx_secure_host_port: 443

# Basic Auth (usuario aquí; password en vault.yml)
nginx_basic_user: "admin"
# basic_auth_user: "admin"

# Carpeta en la VM donde se guardan conf/certs/htpasswd
# nginx_secure_dir: "/home/{{ vm_user }}/nginx-secure"
