$ANSIBLE_VAULT;1.1;AES256
36303339333438623636613963393533323662663763616338313537316135616436323362373132
6639396637656530626533653066393163303031373637650a613236636638616265363931646566
37636538363864336438643966336666383531383163313338343530363966306335373837613236
3837376339643631380a656338393233303963356336633362376264386138343763393436333966
62376661326265633365323533316434643539346330326466623539613132343363313132633331
36633438343162626537346635303637666365353762373736353436373862363836643131343838
32333261643437303538306131363938633238366431613938623337373437346434303333626638
33323131326162383563363533353538346437363561653563653463633338633831366662643961
32383761636233653439633937333063383062326630396363373631643733616530316437356136
36623164383934623762623764626438343233303066336534636434373264393864643331653731
30376464393935623535333630303737316635646332623166316237366433363239376237623236
64376434303631333361636336333338616162643263376261366538343563663039643432643635
61623134303265663361323263303436643565333765323339353962643334343834323361353038
32663434376561363361643134616161643633656635313564396431343832323662333962313764
39383432306466396630643738623939616166366230616232346238306162373134323637386264
32323134373334353330623330383937343537346138373162656634343332363366373836313336
64366165346161653837346432653166663038346331383464333366633166363834346537326438
37363664356132623966633939383737656135373032626331396365336230653631303061626635
34646538633830323337663139323862636639616637343433343631303166616533346632316566
37366663323438616230
