$ANSIBLE_VAULT;1.1;AES256
64326364663230666236346130393664373966313665396261616666623663333437636539623831
6237376564313835656136653434653134343365383364320a636535396236303130396265333039
30393831356434393562653432613364653965623338376466636639666331613739383333326436
6538336666613437620a376131636435656436306636656330373239313232333133623065313939
39643965376236366163653066633261373561393465636238313932326533356337333964646364
64393236636230376632326561643537616661646334373163626330643933313062303866316231
66623062363830653438373034666330366331363762383336363234343138623763343637326662
66313666653866646433643638353262383461386336643563653536363130626336333465326433
66353533376663663337303062643937623132393962653065313961623165303030363339613039
39393865373936303465363335613566636334356134306362383032326239353666343734393633
33363630333939643932623936656636363431353738336238666462626161353036396466643663
62633035646366326165353434623535333665323661383064343035373661353533633335343638
30383765653731613839303935346261656663353661663233366632666266633037616433376336
39363636343365343463616532373834643064333237643134613432666561636537646334356462
30386234636331613466616633313032376333363164346637333238653961346663623462643736
39366663313633353834376437653236353435626334376637336636646235373137666630373165
39643661646132663631643130346266316434653333383733393463626134376365623739306364
62333933626535333664376663633230643661323139623337663534363734633933333930346138
33633063343065643036336433623833346562323534393037343639326331363835396164616165
64356236366666363037
