$ANSIBLE_VAULT;1.1;AES256
39386466326133346330323132623533393432623839616630346333613366383637383130336333
3562663133636231316237336563393038393638616332320a396161373634656330653030343033
64313232646466616534383733373737316631353234616631376631616232366561616538396135
3139396164323563300a663431313134346563343331313864323932616338376530643762356336
35643934383664383863363066613439313534373532393039366662393230636333636632303762
34623935633864623830613032316638613033363361626438373730643834356635313066333062
64333965356163663962353037376663333461646533393061643639666138666436316564663639
64616133663530396237303765653733366338623330346263373866316163343731363561363731
37356434653061646334393661333937393962396163326439356263646631663833313938383363
62353430343831356163666438326562393336356336646538626632366564373334333839626238
30373539623233306565336561303234636162376465616236393732633361353537356366666436
33323338356238663264663335323830346238323833353435356665333730323861303764613164
39323531653930636166613738646531623833323634323564653865393834303333633262313032
30653961616136356464356530616230336464636539633032383364306131613835616434643162
64656334613733356662393361356535336334353430613065313735653537333535643036626165
66353930656564333766313332366563623233396439343130316466353664386133383039623535
31333936323262613262336165646264343139666164396333663663623766633435303061633839
63363233653866666664633563613466633036656161336261336532626435393932376565613563
36663430646337663533363235323631663865636438313161626137623438343233303232306438
65616534636231383438
