---
- name: Aplicar manifiesto AKS renderizado (Azure Vote)
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', playbook_dir ~ '/../templates/k8s-azure-vote.yaml.j2') | from_yaml_all | list }}"