---
- name: Subir im√°genes AKS al ACR (rol existente)
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all/terraform.yml"
    - "{{ playbook_dir }}/../group_vars/all/common.yml"
    - "{{ playbook_dir }}/../group_vars/all/acr.yml"
    - "{{ playbook_dir }}/../group_vars/all/images.yml"
    - "{{ playbook_dir }}/../group_vars/vault.yml"
  roles:
    - acr_push