---
- name: Aplicar manifiesto AKS
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all/common.yml"
    - "{{ playbook_dir }}/../group_vars/all/terraform.yml"
  roles:
    - aks_deploy